<?php

include_once('hosting_project.node.inc');
include_once('hosting_project.form.inc');

/**
 * Implementation of hook_menu().
 */
function hosting_project_menu() {
  $items = array();
  $items['hosting/project'] = array(
    'title' => 'Projects',
    'description' => 'List of projects',
    'page callback' => 'hosting_project_listing',
    'access arguments' => array('view project'));

  $items['hosting/project/access'] = array(
    'title' => 'Access',
    'description' => 'Github oauth callback',
    'page callback' => 'hosting_project_access',
    'access arguments' => array('view project'));

  return $items;
}

/**
 * Implementation of hook_hosting_tasks().
 */
function hosting_project_hosting_tasks() {
  $tasks = array();
  $tasks['project']['deploy'] = array(
    'title' => t('Deploy'),
    'description' => t('Create a deployment'),
    'weight' => 10,
    'dialog' => TRUE,
    'access callback' => 'hosting_project_hosting_task_access',
  );
  return $tasks;
}


function hosting_project_hosting_task_access($node, $task) {
  return TRUE;
}


/**
 * Implementation of hook_perm().
 */
function hosting_project_perm() {
  return array(
    'create deploy task',
  );
}

